query Page(
  $limit: Int!
  $after: ID
  $sort: [PersonSort!]
  $filter: PersonFilters
) {
  persons(after: $after, limit: $limit, sort: $sort, filter: $filter) {
    edges {
      node {
        id
        firstname
        lastname
        gender
        type
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
